/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const physics_core_get_info: () => number;
export const physics_core_free_string: (a: number) => void;
export const wgpu_init: (a: number, b: number, c: number) => number;
export const wgpu_update: (a: number) => void;
export const wgpu_render: () => void;
export const wgpu_resize: (a: number, b: number) => void;
export const wgpu_shutdown: () => void;
export const wasm_get_info: () => [number, number];
export const wasm_init: (a: number, b: number, c: number, d: number) => any;
export const wasm_update: (a: number) => void;
export const wasm_render: () => void;
export const wasm_resize: (a: number, b: number) => void;
export const wasm_shutdown: () => void;
export const wgpu_render_bundle_set_pipeline: (a: number, b: bigint) => void;
export const wgpu_render_bundle_set_bind_group: (a: number, b: number, c: bigint, d: number, e: number) => void;
export const wgpu_render_bundle_set_vertex_buffer: (a: number, b: number, c: bigint, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_set_push_constants: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw: (a: number, b: number, c: number, d: number, e: number) => void;
export const wgpu_render_bundle_draw_indexed: (a: number, b: number, c: number, d: number, e: number, f: number) => void;
export const wgpu_render_bundle_draw_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_draw_indexed_indirect: (a: number, b: bigint, c: bigint) => void;
export const wgpu_render_bundle_set_index_buffer: (a: number, b: bigint, c: number, d: bigint, e: bigint) => void;
export const wgpu_render_bundle_pop_debug_group: (a: number) => void;
export const wgpu_render_bundle_insert_debug_marker: (a: number, b: number) => void;
export const wgpu_render_bundle_push_debug_group: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h8c4b64e1003bd1eb: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__hbe4f64e4a7f56493: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h2722dc08f6e4d727: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h2dd58a0ce178cf60: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h3987b035e3186da2: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
