/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const physics_core_get_info: () => number;
export const update_physics_internal: (a: number, b: number) => void;
export const physics_core_free_string: (a: number) => void;
export const physics_core_set_gravity: (a: number) => void;
export const physics_core_set_time_scale: (a: number) => void;
export const physics_core_set_paused: (a: number) => void;
export const physics_core_reset_simulation: () => void;
export const wgpu_init: (a: number, b: number, c: number) => number;
export const wgpu_update: (a: number) => void;
export const wgpu_render: () => void;
export const wgpu_resize: (a: number, b: number) => void;
export const wgpu_shutdown: () => void;
export const wasm_get_info: () => [number, number];
export const wasm_init: (a: number, b: number, c: number, d: number) => any;
export const wasm_update: (a: number) => void;
export const wasm_render: () => void;
export const wasm_resize: (a: number, b: number) => void;
export const wasm_shutdown: () => void;
export const wasm_set_paused: (a: number) => void;
export const wasm_reset_simulation: () => void;
export const wasm_set_gravity: (a: number) => void;
export const wasm_set_time_scale: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h62e53448fb7e4d31: (a: number, b: number, c: any) => void;
export const wasm_bindgen__closure__destroy__h7247d2cb8ecc6b8d: (a: number, b: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h404c9f566fafd69f: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
